{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyNekH3R2YCq1QqWE6OIXX+c",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/Shri2783/AQI-CHILID-HEALTH/blob/main/app.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 8,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "C94z14DPni0h",
        "outputId": "cf0e7ae6-71b6-4208-b3cc-11fbf9f8b600"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stderr",
          "text": [
            "2026-04-13 07:16:58.409 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-04-13 07:16:58.410 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-04-13 07:16:58.411 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-04-13 07:16:58.413 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-04-13 07:16:58.418 No runtime found, using MemoryCacheStorageManager\n",
            "2026-04-13 07:16:58.421 No runtime found, using MemoryCacheStorageManager\n",
            "2026-04-13 07:16:58.422 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-04-13 07:16:58.662 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-04-13 07:16:58.662 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-04-13 07:16:58.664 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-04-13 07:16:58.668 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-04-13 07:16:58.669 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-04-13 07:16:58.671 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-04-13 07:16:58.674 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-04-13 07:16:58.677 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-04-13 07:16:58.678 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-04-13 07:16:58.679 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-04-13 07:16:58.680 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-04-13 07:16:58.683 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-04-13 07:16:58.684 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-04-13 07:16:58.686 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-04-13 07:16:58.687 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-04-13 07:16:58.689 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-04-13 07:16:58.691 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-04-13 07:16:58.692 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-04-13 07:16:58.692 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-04-13 07:16:58.693 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-04-13 07:16:58.694 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-04-13 07:16:58.695 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-04-13 07:16:58.696 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-04-13 07:16:58.696 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-04-13 07:16:58.698 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-04-13 07:16:58.698 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-04-13 07:16:58.699 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-04-13 07:16:58.699 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-04-13 07:16:58.709 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-04-13 07:16:58.711 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-04-13 07:16:58.712 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-04-13 07:16:58.713 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-04-13 07:16:58.713 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-04-13 07:16:58.715 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-04-13 07:16:58.715 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-04-13 07:16:58.718 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-04-13 07:16:58.719 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-04-13 07:16:58.719 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-04-13 07:16:58.720 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-04-13 07:16:58.721 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-04-13 07:16:58.721 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-04-13 07:16:58.722 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-04-13 07:16:58.724 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-04-13 07:16:58.729 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-04-13 07:16:58.730 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-04-13 07:16:58.731 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-04-13 07:16:58.731 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-04-13 07:16:58.732 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-04-13 07:16:58.732 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-04-13 07:16:58.734 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-04-13 07:16:58.734 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-04-13 07:16:58.735 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-04-13 07:16:58.736 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-04-13 07:16:58.736 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-04-13 07:16:58.737 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-04-13 07:16:58.737 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-04-13 07:16:58.739 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-04-13 07:16:58.739 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-04-13 07:16:58.740 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-04-13 07:16:58.740 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-04-13 07:16:58.741 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-04-13 07:16:58.742 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-04-13 07:16:58.743 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-04-13 07:16:58.744 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-04-13 07:16:58.745 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-04-13 07:16:58.745 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-04-13 07:16:58.746 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-04-13 07:16:58.835 Please replace `use_container_width` with `width`.\n",
            "\n",
            "`use_container_width` will be removed after 2025-12-31.\n",
            "\n",
            "For `use_container_width=True`, use `width='stretch'`. For `use_container_width=False`, use `width='content'`.\n",
            "2026-04-13 07:16:58.837 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-04-13 07:16:58.839 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-04-13 07:16:58.840 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-04-13 07:16:58.841 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-04-13 07:16:58.842 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-04-13 07:16:58.844 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-04-13 07:16:58.845 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-04-13 07:16:58.846 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-04-13 07:16:58.848 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-04-13 07:16:58.849 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-04-13 07:16:58.852 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-04-13 07:16:58.853 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-04-13 07:16:58.854 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-04-13 07:16:58.856 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-04-13 07:16:58.856 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-04-13 07:16:58.857 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-04-13 07:16:58.858 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-04-13 07:16:58.859 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-04-13 07:16:58.860 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-04-13 07:16:58.863 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-04-13 07:16:58.864 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-04-13 07:16:58.865 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-04-13 07:16:58.865 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-04-13 07:16:58.866 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-04-13 07:16:58.868 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-04-13 07:16:58.868 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n"
          ]
        }
      ],
      "source": [
        "import streamlit as st\n",
        "import pandas as pd\n",
        "import numpy as np\n",
        "import plotly.express as px\n",
        "import plotly.graph_objects as go\n",
        "from scipy import stats\n",
        "from sklearn.preprocessing import MinMaxScaler\n",
        "import os\n",
        "\n",
        "st.set_page_config(\n",
        "    page_title=\"AQI & Child Health India\",\n",
        "    page_icon=\"🌫️\",\n",
        "    layout=\"wide\",\n",
        "    initial_sidebar_state=\"expanded\"\n",
        ")\n",
        "\n",
        "st.markdown(\"\"\"\n",
        "<style>\n",
        ".kpi{background:#f8f9fa;border-radius:10px;padding:16px 10px;text-align:center;border:1px solid #e0e0e0}\n",
        ".kpi-val{font-size:1.9rem;font-weight:700}\n",
        ".kpi-lbl{font-size:0.78rem;color:#666;margin-top:2px}\n",
        ".insight{border-left:4px solid;padding:12px 16px;margin:8px 0;font-size:0.9rem;line-height:1.6;border-radius:0 8px 8px 0}\n",
        ".insight.red{border-color:#e74c3c;background:#fff5f5;color:#7b1f1f}\n",
        ".insight.green{border-color:#27ae60;background:#f0fff4;color:#1a4731}\n",
        ".insight.amber{border-color:#e67e22;background:#fffaf0;color:#6b3a0e}\n",
        ".insight.blue{border-color:#2980b9;background:#eef6fd;color:#1a3a52}\n",
        ".sol{border-radius:10px;padding:16px;margin-bottom:10px}\n",
        ".sol.urgent{background:#fff0f0;border:1px solid #f5b7b1}\n",
        ".sol.mid{background:#fffbf0;border:1px solid #fad7a0}\n",
        ".sol.long{background:#f0fff4;border:1px solid #a9dfbf}\n",
        ".discuss{background:#f0f4ff;border-radius:8px;padding:12px 16px;margin:8px 0;font-size:0.9rem;border-left:3px solid #3498db}\n",
        ".badge{display:inline-block;padding:2px 9px;border-radius:12px;font-size:0.72rem;font-weight:600;margin-left:6px}\n",
        ".bc{background:#e74c3c;color:white}\n",
        ".bh{background:#e67e22;color:white}\n",
        ".bm{background:#f1c40f;color:#333}\n",
        ".bg{background:#27ae60;color:white}\n",
        "</style>\n",
        "\"\"\", unsafe_allow_html=True)\n",
        "\n",
        "BASE = '/content/' # os.path.dirname(os.path.abspath(__file__))\n",
        "AQI_FILE = os.path.join(BASE, \"city_day.csv\")\n",
        "NFHS_FILE= os.path.join(BASE, \"NFHS_5_India_Districts_Factsheet_Data.csv\")\n",
        "\n",
        "@st.cache_data\n",
        "def load_data():\n",
        "    city_state = {\n",
        "        'Ahmedabad':'Gujarat','Aizawl':'Mizoram','Amaravati':'Maharashtra',\n",
        "        'Amritsar':'Punjab','Bengaluru':'Karnataka','Bhopal':'Madhya Pradesh',\n",
        "        'Brajrajnagar':'Odisha','Chandigarh':'Chandigarh','Chennai':'Tamil Nadu',\n",
        "        'Coimbatore':'Tamil Nadu','Delhi':'Delhi','Ernakulam':'Kerala',\n",
        "        'Gurugram':'Haryana','Guwahati':'Assam','Hyderabad':'Telangana',\n",
        "        'Jaipur':'Rajasthan','Jorapokhar':'Jharkhand','Kochi':'Kerala',\n",
        "        'Kolkata':'West Bengal','Lucknow':'Uttar Pradesh','Mumbai':'Maharashtra',\n",
        "        'Patna':'Bihar','Shillong':'Meghalaya','Talcher':'Odisha',\n",
        "        'Thiruvananthapuram':'Kerala','Visakhapatnam':'Andhra Pradesh',\n",
        "    }\n",
        "    aqi_raw          = pd.read_csv(AQI_FILE)\n",
        "    aqi_raw['Date']  = pd.to_datetime(aqi_raw['Date'], dayfirst=True, errors='coerce')\n",
        "    aqi_raw['State'] = aqi_raw['City'].map(city_state)\n",
        "    aqi_raw['Year']  = aqi_raw['Date'].dt.year\n",
        "    aqi_full         = aqi_raw.dropna(subset=['State'])\n",
        "    aqi              = aqi_full[aqi_full['Year'].between(2015, 2019)].copy()\n",
        "\n",
        "    aqi_state = aqi.groupby('State').agg(\n",
        "        mean_AQI=('AQI','mean'), median_AQI=('AQI','median'),\n",
        "        mean_PM25=('PM2.5','mean'), mean_PM10=('PM10','mean'),\n",
        "        mean_NO2=('NO2','mean'), mean_SO2=('SO2','mean'),\n",
        "        mean_O3=('O3','mean'), n_records=('AQI','count'),\n",
        "    ).reset_index()\n",
        "\n",
        "    def clean(c):\n",
        "        return pd.to_numeric(\n",
        "            c.astype(str).str.replace(r'[\\(\\)]','',regex=True).str.strip(),\n",
        "            errors='coerce')\n",
        "\n",
        "    nfhs = pd.read_csv(NFHS_FILE, encoding='latin1')\n",
        "    nfhs.rename(columns={\n",
        "        'State/UT':'State',\n",
        "        'Children Prevalence of symptoms of acute respiratory infection (ARI) in the 2 weeks preceding the survey (Children under age 5 years) (%) ':'ARI_pct',\n",
        "        'Children under 5 years who are stunted (height-for-age)18 (%)':'Stunting_pct',\n",
        "        'Children under 5 years who are underweight (weight-for-age)18 (%)':'Underweight_pct',\n",
        "        'Children age 6-59 months who are anaemic (<11.0 g/dl)22 (%)':'Anaemia_pct',\n",
        "    }, inplace=True)\n",
        "    for c in ['ARI_pct','Stunting_pct','Underweight_pct','Anaemia_pct']:\n",
        "        nfhs[c] = clean(nfhs[c])\n",
        "    nfhs_s = nfhs.groupby('State')[['ARI_pct','Stunting_pct',\n",
        "                                     'Underweight_pct','Anaemia_pct']].mean().reset_index()\n",
        "    for df in [aqi_state, nfhs_s]:\n",
        "        df['State'] = df['State'].str.strip().str.title()\n",
        "\n",
        "    m = pd.merge(aqi_state, nfhs_s, on='State', how='inner')\n",
        "\n",
        "    def cat(v):\n",
        "        if v<=50:   return 'Good'\n",
        "        elif v<=100: return 'Satisfactory'\n",
        "        elif v<=200: return 'Moderate'\n",
        "        elif v<=300: return 'Poor'\n",
        "        else:        return 'Very Poor'\n",
        "\n",
        "    m['AQI_Category'] = m['mean_AQI'].apply(cat)\n",
        "    m['AQI_Group']    = np.where(m['mean_AQI'] >= m['mean_AQI'].median(), 'High', 'Low')\n",
        "\n",
        "    def g3(v):\n",
        "        return 'Good / Satisfactory' if v<=100 else ('Moderate' if v<=200 else 'Poor / Very Poor')\n",
        "    m['AQI_Group3'] = m['mean_AQI'].apply(g3)\n",
        "\n",
        "    sc = MinMaxScaler()\n",
        "    hc = ['ARI_pct','Stunting_pct','Underweight_pct','Anaemia_pct']\n",
        "    m['Health_Index'] = sc.fit_transform(m[hc]).mean(axis=1)\n",
        "    m['AQI_norm']     = sc.fit_transform(m[['mean_AQI']])\n",
        "\n",
        "    am = m['AQI_norm'].median()\n",
        "    hm = m['Health_Index'].median()\n",
        "    def quad(r):\n",
        "        ha = r['AQI_norm']    >= am\n",
        "        hh = r['Health_Index'] >= hm\n",
        "        if   ha and hh:      return 'High Risk'\n",
        "        elif not ha and hh:  return 'Health Concern'\n",
        "        elif ha and not hh:  return 'Air Quality Concern'\n",
        "        else:                return 'Favourable'\n",
        "    m['Quadrant'] = m.apply(quad, axis=1)\n",
        "\n",
        "    for hv in hc:\n",
        "        m[hv+'_bin'] = (m[hv] >= m[hv].median()).astype(int)\n",
        "\n",
        "    return m, aqi_full, aqi_raw\n",
        "\n",
        "try:\n",
        "    merged, aqi_full, aqi_raw = load_data()\n",
        "except FileNotFoundError as e:\n",
        "    st.error(f\"❌ File not found: {e}\\n\\nEnsure city_day.csv and \"\n",
        "             \"NFHS_5_India_Districts_Factsheet_Data.csv are in the repo root.\")\n",
        "    st.stop()\n",
        "\n",
        "HV = ['ARI_pct','Stunting_pct','Underweight_pct','Anaemia_pct']\n",
        "HL = {'ARI_pct':'ARI (%)','Stunting_pct':'Stunting (%)','Underweight_pct':'Underweight (%)','Anaemia_pct':'Anaemia (%)'}\n",
        "PV = ['mean_AQI','mean_PM25','mean_PM10','mean_NO2','mean_SO2','mean_O3']\n",
        "CC = {'Good':'#27ae60','Satisfactory':'#2ecc71','Moderate':'#f39c12','Poor':'#e67e22','Very Poor':'#e74c3c'}\n",
        "QC = {'High Risk':'#e74c3c','Health Concern':'#e67e22','Air Quality Concern':'#3498db','Favourable':'#27ae60'}\n",
        "O3 = ['Good / Satisfactory','Moderate','Poor / Very Poor']\n",
        "\n",
        "def sig(p):\n",
        "    return '★★★' if p<0.001 else ('★★' if p<0.01 else ('★ p<0.05' if p<0.05 else 'ns'))\n",
        "\n",
        "with st.sidebar:\n",
        "    st.markdown(\"## 🌫️ AQI & Child Health\")\n",
        "    st.markdown(\"*India — Non-Parametric Study*\")\n",
        "    st.caption(\"CPCB (2015–2019) + NFHS-5 (2019–21)\")\n",
        "    st.divider()\n",
        "    page = st.radio(\"Navigate to\", [\n",
        "        \"🏠  Overview\",\n",
        "        \"📊  EDA Explorer\",\n",
        "        \"🧪  Statistical Tests\",\n",
        "        \"💡  Insights\",\n",
        "        \"🛠️  Solutions\",\n",
        "        \"🗣️  Discussion Guide\",\n",
        "    ])\n",
        "    st.divider()\n",
        "    st.caption(\"Shrigothay A · 22MIY0014\")\n",
        "    st.caption(f\"States: **{merged.shape[0]}** | Records: **{len(aqi_full):,}**\")\n",
        "\n",
        "# ── PAGE 1: OVERVIEW ─────────────────────────────────────────\n",
        "if page == \"🏠  Overview\":\n",
        "    st.title(\"🌫️ Urban Air Quality & Child Health in India\")\n",
        "    st.markdown(\"**Non-Parametric Analysis** | CPCB + NFHS-5 | 18 States\")\n",
        "    st.info(\"💡 Navigate using the sidebar to explore data, run tests, view insights and solutions.\")\n",
        "\n",
        "    c1,c2,c3,c4,c5 = st.columns(5)\n",
        "    for col,val,lbl,color in zip([c1,c2,c3,c4,c5],\n",
        "        [merged.shape[0], aqi_full['City'].nunique(), f\"{len(aqi_full):,}\",\n",
        "         (merged['Quadrant']=='High Risk').sum(), \"4\"],\n",
        "        [\"States\",\"Cities\",\"AQI records\",\"High-risk states\",\"Tests\"],\n",
        "        [\"#3498db\",\"#27ae60\",\"#9b59b6\",\"#e74c3c\",\"#e67e22\"]):\n",
        "        col.markdown(f'<div class=\"kpi\"><div class=\"kpi-val\" style=\"color:{color}\">{val}</div>'\n",
        "                     f'<div class=\"kpi-lbl\">{lbl}</div></div>', unsafe_allow_html=True)\n",
        "\n",
        "    st.divider()\n",
        "    col1,col2 = st.columns([3,2])\n",
        "    with col1:\n",
        "        st.subheader(\"State-wise Mean AQI (2015–2019)\")\n",
        "        fig = px.bar(merged.sort_values('mean_AQI',ascending=True),\n",
        "                     x='mean_AQI', y='State', color='AQI_Category',\n",
        "                     color_discrete_map=CC, orientation='h', height=560,\n",
        "                     labels={'mean_AQI':'Mean AQI','State':''})\n",
        "        fig.add_vline(x=100, line_dash='dash', line_color='red',\n",
        "                      annotation_text='Moderate threshold')\n",
        "        fig.update_layout(plot_bgcolor='white', margin=dict(l=0,r=10,t=10,b=0))\n",
        "        st.plotly_chart(fig, use_container_width=True)\n",
        "\n",
        "    with col2:\n",
        "        st.subheader(\"Key findings\")\n",
        "        for name,stat,pval,color in [\n",
        "            (\"AQI vs Anaemia\",\"ρ=+0.550\",\"p=0.018\",\"#27ae60\"),\n",
        "            (\"AQI vs Underweight\",\"ρ=+0.505\",\"p=0.033\",\"#27ae60\"),\n",
        "            (\"Mann–Whitney Anaemia\",\"r=−0.630\",\"p=0.027\",\"#27ae60\"),\n",
        "            (\"Mann–Whitney Underweight\",\"r=−0.630\",\"p=0.027\",\"#27ae60\"),\n",
        "            (\"Kruskal–Wallis Anaemia\",\"H=5.890\",\"p=0.053\",\"#e67e22\"),\n",
        "        ]:\n",
        "            st.markdown(f'<div style=\"display:flex;justify-content:space-between;'\n",
        "                        f'padding:6px 10px;border-radius:6px;background:#f8f9fa;'\n",
        "                        f'margin:3px 0;font-size:13px\"><span>{name}</span>'\n",
        "                        f'<span style=\"font-weight:600;color:{color}\">{stat} · {pval}</span>'\n",
        "                        f'</div>', unsafe_allow_html=True)\n",
        "        st.markdown(\"\"\"---\n",
        "**7 HIGH RISK states:** Bihar, Gujarat, Jharkhand, Madhya Pradesh, Rajasthan, UP, West Bengal\n",
        "\n",
        "**Benchmark:** Kerala (lowest AQI + best child health)\n",
        "        \"\"\")\n",
        "\n",
        "# ── PAGE 2: EDA ───────────────────────────────────────────────\n",
        "elif page == \"📊  EDA Explorer\":\n",
        "    st.title(\"📊 EDA Explorer\")\n",
        "    tab1,tab2,tab3,tab4 = st.tabs([\"🏙️ City Trends\",\"📍 State vs Health\",\"🔬 Pollutants\",\"📋 Stats\"])\n",
        "\n",
        "    with tab1:\n",
        "        c1,c2 = st.columns(2)\n",
        "        with c1:\n",
        "            sel = st.multiselect(\"Cities\", sorted(aqi_raw['City'].dropna().unique()),\n",
        "                                  default=['Delhi','Mumbai','Chennai','Kolkata','Patna'])\n",
        "        with c2:\n",
        "            yr = st.slider(\"Year range\", 2015, 2024, (2015,2019))\n",
        "        df_t = aqi_raw[aqi_raw['City'].isin(sel) & aqi_raw['Year'].between(yr[0],yr[1])].dropna(subset=['AQI'])\n",
        "        df_t['Month'] = df_t['Date'].dt.to_period('M').astype(str)\n",
        "        monthly = df_t.groupby(['Month','City'])['AQI'].mean().reset_index()\n",
        "        fig = px.line(monthly, x='Month', y='AQI', color='City', height=420,\n",
        "                      title=f'Monthly mean AQI — {yr[0]} to {yr[1]}')\n",
        "        fig.add_hline(y=100, line_dash='dash', line_color='orange', annotation_text='Moderate')\n",
        "        fig.add_hline(y=200, line_dash='dash', line_color='red', annotation_text='Poor')\n",
        "        fig.update_xaxes(tickangle=45)\n",
        "        fig.update_layout(plot_bgcolor='white')\n",
        "        st.plotly_chart(fig, use_container_width=True)\n",
        "        st.info(\"Delhi and Patna spike in Oct–Jan (winter crop burning). Southern cities stay below 100 year-round.\")\n",
        "\n",
        "    with tab2:\n",
        "        c1,c2 = st.columns(2)\n",
        "        with c1: xv = st.selectbox(\"X (pollutant)\", PV)\n",
        "        with c2: yv = st.selectbox(\"Y (health)\", HV, format_func=lambda x: HL[x])\n",
        "        fig = px.scatter(merged, x=xv, y=yv, text='State', color='AQI_Category',\n",
        "                         size='n_records', trendline='ols', color_discrete_map=CC,\n",
        "                         hover_data=['State','mean_AQI','Anaemia_pct'],\n",
        "                         title=f'{xv} vs {HL[yv]}', height=500)\n",
        "        fig.update_traces(textposition='top center', marker_opacity=0.85)\n",
        "        fig.update_layout(plot_bgcolor='white')\n",
        "        st.plotly_chart(fig, use_container_width=True)\n",
        "        st.info(\"Positive trendline = higher pollution → worse health. Top-right states = highest priority.\")\n",
        "\n",
        "    with tab3:\n",
        "        state_sel = st.multiselect(\"States\",sorted(merged['State'].tolist()),\n",
        "                                    default=merged.sort_values('mean_AQI',ascending=False)['State'].head(6).tolist())\n",
        "        poll_map = {'mean_PM25':'PM2.5','mean_PM10':'PM10','mean_NO2':'NO₂','mean_SO2':'SO₂','mean_O3':'O₃'}\n",
        "        df_p = merged[merged['State'].isin(state_sel)][['State']+list(poll_map.keys())].copy()\n",
        "        df_p.columns = ['State']+list(poll_map.values())\n",
        "        df_melt = df_p.melt(id_vars='State', var_name='Pollutant', value_name='Concentration')\n",
        "        fig = px.bar(df_melt, x='Pollutant', y='Concentration', color='State',\n",
        "                     barmode='group', height=420, title='Pollutant concentrations by state')\n",
        "        fig.update_layout(plot_bgcolor='white')\n",
        "        st.plotly_chart(fig, use_container_width=True)\n",
        "\n",
        "    with tab4:\n",
        "        st.dataframe(merged[['mean_AQI','mean_PM25','mean_PM10','ARI_pct',\n",
        "                              'Stunting_pct','Anaemia_pct','Underweight_pct']].describe().round(2),\n",
        "                     use_container_width=True)\n",
        "        st.dataframe(merged[['State','AQI_Category','mean_AQI','ARI_pct','Stunting_pct',\n",
        "                              'Anaemia_pct','Underweight_pct','Quadrant']].sort_values('mean_AQI',ascending=False).round(2),\n",
        "                     use_container_width=True)\n",
        "\n",
        "# ── PAGE 3: STATISTICAL TESTS ─────────────────────────────────\n",
        "elif page == \"🧪  Statistical Tests\":\n",
        "    st.title(\"🧪 Statistical Tests\")\n",
        "    tab1,tab2,tab3,tab4 = st.tabs([\"1″️ Spearman\",\"2″️ Kruskal–Wallis\",\"3″️ Mann–Whitney\",\"4″️ Chi-Square\"])\n",
        "\n",
        "    with tab1:\n",
        "        st.markdown(\"### Spearman rank correlation\")\n",
        "        poll_s = st.selectbox(\"Pollutant\", PV, key='sp')\n",
        "        rows = []\n",
        "        for hv in HV:\n",
        "            d = merged[[poll_s,hv]].dropna()\n",
        "            rho,p = stats.spearmanr(d[poll_s], d[hv])\n",
        "            rows.append({'Health indicator':HL[hv],'Spearman ρ':round(rho,3),\n",
        "                         'p-value':round(p,4),'n':len(d),'Result':sig(p)})\n",
        "        st.dataframe(pd.DataFrame(rows), use_container_width=True)\n",
        "        st.caption(\"★★★ p<0.001 | ★★ p<0.01 | ★ p<0.05 | ns = not significant\")\n",
        "\n",
        "        rho_mat = {}\n",
        "        for hv in HV:\n",
        "            rho_mat[HL[hv]] = {}\n",
        "            for pv in PV:\n",
        "                d = merged[[pv,hv]].dropna()\n",
        "                rho,_ = stats.spearmanr(d[pv],d[hv]) if len(d)>=3 else (np.nan,1)\n",
        "                rho_mat[HL[hv]][pv.replace('mean_','')] = round(rho,3)\n",
        "        fig = px.imshow(pd.DataFrame(rho_mat).T, text_auto=True,\n",
        "                        color_continuous_scale='RdYlGn', zmin=-1, zmax=1,\n",
        "                        title=\"Spearman ρ heatmap — all pairs\", height=360)\n",
        "        st.plotly_chart(fig, use_container_width=True)\n",
        "        st.markdown('<div class=\"insight blue\">AQI vs Anaemia ρ=+0.550 (p=0.018) and AQI vs Underweight ρ=+0.505 (p=0.033) are both statistically significant with medium-to-large effect sizes.</div>', unsafe_allow_html=True)\n",
        "\n",
        "    with tab2:\n",
        "        st.markdown(\"### Kruskal–Wallis test\")\n",
        "        hv2 = st.selectbox(\"Health outcome\", HV, format_func=lambda x: HL[x], key='kw')\n",
        "        groups = [merged[merged['AQI_Group3']==g][hv2].dropna() for g in O3]\n",
        "        groups = [g for g in groups if len(g)>0]\n",
        "        H,p = stats.kruskal(*groups)\n",
        "        c1,c2,c3 = st.columns(3)\n",
        "        c1.metric(\"H-statistic\", f\"{H:.3f}\")\n",
        "        c2.metric(\"p-value\", f\"{p:.4f}\")\n",
        "        c3.metric(\"Significance\", sig(p))\n",
        "        fig = px.violin(merged, x='AQI_Group3', y=hv2,\n",
        "                        category_orders={'AQI_Group3':O3},\n",
        "                        color='AQI_Group3', box=True, points='all',\n",
        "                        color_discrete_sequence=['#27ae60','#f39c12','#e74c3c'],\n",
        "                        hover_data=['State'], title=f'{HL[hv2]} across AQI groups', height=420)\n",
        "        fig.update_layout(plot_bgcolor='white', showlegend=False)\n",
        "        st.plotly_chart(fig, use_container_width=True)\n",
        "        kw_all = []\n",
        "        for hv in HV:\n",
        "            gs = [merged[merged['AQI_Group3']==g][hv].dropna() for g in O3]\n",
        "            gs = [g for g in gs if len(g)>0]\n",
        "            H2,p2 = stats.kruskal(*gs)\n",
        "            kw_all.append({'Outcome':HL[hv],'H':round(H2,3),'p-value':round(p2,4),'Result':sig(p2)})\n",
        "        st.dataframe(pd.DataFrame(kw_all), use_container_width=True)\n",
        "        st.markdown('<div class=\"insight amber\">Anaemia shows marginal trend (p=0.053). Non-significance is partly due to unequal group sizes (Moderate group = 11/18 states).</div>', unsafe_allow_html=True)\n",
        "\n",
        "    with tab3:\n",
        "        st.markdown(\"### Mann–Whitney U test\")\n",
        "        med_aqi = merged['mean_AQI'].median()\n",
        "        st.info(f\"Median AQI split = **{med_aqi:.1f}** | High: {(merged['AQI_Group']=='High').sum()} states | Low: {(merged['AQI_Group']=='Low').sum()} states\")\n",
        "        mw_rows = []\n",
        "        for hv in HV:\n",
        "            h = merged[merged['AQI_Group']=='High'][hv].dropna()\n",
        "            l = merged[merged['AQI_Group']=='Low'][hv].dropna()\n",
        "            U,p = stats.mannwhitneyu(h, l, alternative='two-sided')\n",
        "            r = round(1-(2*U)/(len(h)*len(l)),3)\n",
        "            diff = round(h.mean()-l.mean(),2)\n",
        "            mw_rows.append({'Outcome':HL[hv],'U':round(U),'p-value':round(p,4),\n",
        "                            'Effect r':r,'Mean High':round(h.mean(),2),\n",
        "                            'Mean Low':round(l.mean(),2),\n",
        "                            'Difference':f\"+{diff}\" if diff>0 else str(diff),'Result':sig(p)})\n",
        "        st.dataframe(pd.DataFrame(mw_rows), use_container_width=True)\n",
        "        hv3 = st.selectbox(\"Visualise\", HV, format_func=lambda x: HL[x], key='mw3')\n",
        "        fig = px.box(merged, x='AQI_Group', y=hv3, color='AQI_Group',\n",
        "                     color_discrete_map={'High':'#e74c3c','Low':'#27ae60'},\n",
        "                     points='all', hover_data=['State'],\n",
        "                     title=f'{HL[hv3]}: High vs Low AQI', height=420)\n",
        "        fig.update_layout(plot_bgcolor='white', showlegend=False)\n",
        "        st.plotly_chart(fig, use_container_width=True)\n",
        "        st.markdown('<div class=\"insight blue\">Effect size r=−0.630 is LARGE for both anaemia and underweight. High AQI states have 11.4% more anaemia and 7.8% more underweight children.</div>', unsafe_allow_html=True)\n",
        "\n",
        "    with tab4:\n",
        "        st.markdown(\"### Chi-square + Cramér's V\")\n",
        "        chi_rows = []\n",
        "        for hv in HV:\n",
        "            ct = pd.crosstab(merged['AQI_Group'], merged[hv+'_bin'])\n",
        "            chi2,p,dof,_ = stats.chi2_contingency(ct)\n",
        "            n = ct.values.sum()\n",
        "            v = round(np.sqrt(chi2/(n*(min(ct.shape)-1))),3)\n",
        "            chi_rows.append({'Outcome':HL[hv],'Chi²':round(chi2,3),'p-value':round(p,4),\n",
        "                             \"Cramér's V\":v,'Effect':('Large' if v>0.5 else ('Medium' if v>0.3 else 'Small')),'Result':sig(p)})\n",
        "        st.dataframe(pd.DataFrame(chi_rows), use_container_width=True)\n",
        "        hv4 = st.selectbox(\"Visualise\", HV, format_func=lambda x: HL[x], key='ch4')\n",
        "        ct_n = pd.crosstab(merged['AQI_Group'], merged[hv4+'_bin'], normalize='index')*100\n",
        "        ct_n.columns = ['Below median','Above median']\n",
        "        ct_melt = ct_n.reset_index().melt(id_vars='AQI_Group', var_name='Outcome', value_name='Pct')\n",
        "        fig = px.bar(ct_melt, x='AQI_Group', y='Pct', color='Outcome',\n",
        "                     color_discrete_map={'Below median':'#27ae60','Above median':'#e74c3c'},\n",
        "                     title=f'{HL[hv4]}: above vs below median', height=380)\n",
        "        fig.update_layout(plot_bgcolor='white')\n",
        "        st.plotly_chart(fig, use_container_width=True)\n",
        "        st.markdown('<div class=\"insight amber\">Cramér\\'s V=0.222 shows consistent small-medium association. Chi-square is ns due to small 2×2 table with n=18.</div>', unsafe_allow_html=True)\n",
        "\n",
        "# ── PAGE 4: INSIGHTS ──────────────────────────────────────────\n",
        "elif page == \"💡  Insights\":\n",
        "    st.title(\"💡 Insights\")\n",
        "    am = merged['AQI_norm'].median()\n",
        "    hm = merged['Health_Index'].median()\n",
        "    fig = px.scatter(merged, x='AQI_norm', y='Health_Index', text='State', color='Quadrant',\n",
        "                     color_discrete_map=QC, height=540,\n",
        "                     hover_data={'mean_AQI':':.1f','ARI_pct':':.1f','Stunting_pct':':.1f','Anaemia_pct':':.1f'},\n",
        "                     title='Quadrant: pollution burden vs child health burden',\n",
        "                     labels={'AQI_norm':'Normalised AQI','Health_Index':'Child health risk index'})\n",
        "    fig.add_vline(x=am, line_dash='dash', line_color='gray', opacity=0.4)\n",
        "    fig.add_hline(y=hm, line_dash='dash', line_color='gray', opacity=0.4)\n",
        "    fig.update_traces(textposition='top center', marker=dict(size=14, opacity=0.85))\n",
        "    fig.update_layout(plot_bgcolor='white')\n",
        "    for txt,x,y,col in [(\"HIGH RISK\",0.88,0.95,'#e74c3c'),(\"Health concern\",0.06,0.95,'#e67e22'),\n",
        "                         (\"Air quality concern\",0.78,0.05,'#3498db'),(\"Favourable\",0.06,0.05,'#27ae60')]:\n",
        "        fig.add_annotation(x=x,y=y,text=txt,showarrow=False,font=dict(size=10,color=col),xref='paper',yref='paper')\n",
        "    st.plotly_chart(fig, use_container_width=True)\n",
        "    st.divider()\n",
        "    col1,col2 = st.columns(2)\n",
        "    with col1:\n",
        "        st.subheader(\"🚨 HIGH RISK states\")\n",
        "        for _,row in merged[merged['Quadrant']=='High Risk'].sort_values('mean_AQI',ascending=False).iterrows():\n",
        "            st.markdown(f'<div class=\"insight red\"><b>{row[\"State\"]}</b> — AQI: {row[\"mean_AQI\"]:.0f} | '\n",
        "                        f'Anaemia: {row[\"Anaemia_pct\"]:.1f}% | Underweight: {row[\"Underweight_pct\"]:.1f}%</div>',\n",
        "                        unsafe_allow_html=True)\n",
        "    with col2:\n",
        "        st.subheader(\"✅ Favourable states\")\n",
        "        for _,row in merged[merged['Quadrant']=='Favourable'].sort_values('mean_AQI').iterrows():\n",
        "            st.markdown(f'<div class=\"insight green\"><b>{row[\"State\"]}</b> — AQI: {row[\"mean_AQI\"]:.0f} | '\n",
        "                        f'Anaemia: {row[\"Anaemia_pct\"]:.1f}% | Stunting: {row[\"Stunting_pct\"]:.1f}%</div>',\n",
        "                        unsafe_allow_html=True)\n",
        "    st.divider()\n",
        "    st.markdown('<div class=\"insight blue\"><b>Why does PM2.5 cause anaemia?</b> PM2.5 crosses the alveolar membrane into the bloodstream → triggers IL-6 and TNF-α → upregulates hepcidin → suppresses iron absorption → anaemia. Same inflammatory pathway disrupts growth hormone signalling → stunting and underweight. This is why AQI correlates with nutritional outcomes, not just ARI.</div>', unsafe_allow_html=True)\n",
        "    st.markdown('<div class=\"insight green\"><b>Why is Kerala the benchmark?</b> Lowest anaemia (38.3%), AQI=77.9, high maternal education, strong ICDS, clean cooking fuel adoption. Replicating Kerala\\'s integrated model in HIGH RISK states is the long-term policy goal.</div>', unsafe_allow_html=True)\n",
        "\n",
        "# ── PAGE 5: SOLUTIONS ─────────────────────────────────────────\n",
        "elif page == \"🛠️  Solutions\":\n",
        "    st.title(\"🛠️ Solutions\")\n",
        "    c1,c2,c3 = st.columns(3)\n",
        "    with c1:\n",
        "        st.markdown('<div class=\"sol urgent\"><h4 style=\"color:#a93226;margin:0 0 8px\">🔴 Immediate (0–6 months)</h4><ul style=\"margin:0;padding-left:18px;font-size:0.87rem;line-height:2\"><li>AQI alerts to ASHA workers in Bihar, UP, Jharkhand</li><li>Emergency IFA distribution in Gujarat (anaemia 79.8%), Rajasthan (72.2%)</li><li>ARI surveillance Oct–Jan season</li><li>Outdoor advisories for under-5 children when AQI &gt;200</li></ul></div>', unsafe_allow_html=True)\n",
        "    with c2:\n",
        "        st.markdown('<div class=\"sol mid\"><h4 style=\"color:#9a7d0a;margin:0 0 8px\">🟡 Short-term (6–18 months)</h4><ul style=\"margin:0;padding-left:18px;font-size:0.87rem;line-height:2\"><li>Integrate AQI into district HMIS health reporting</li><li>PM2.5 source attribution in Gujarat + UP</li><li>Crop residue management Punjab/Haryana</li><li>Train paediatric workers on pollution-anaemia link</li></ul></div>', unsafe_allow_html=True)\n",
        "    with c3:\n",
        "        st.markdown('<div class=\"sol long\"><h4 style=\"color:#1e8449;margin:0 0 8px\">🟢 Long-term (2–5 years)</h4><ul style=\"margin:0;padding-left:18px;font-size:0.87rem;line-height:2\"><li>100% LPG in HIGH RISK states (PMUY expansion)</li><li>National AQI–Child Health surveillance system</li><li>Longitudinal cohort study HIGH vs LOW AQI districts</li><li>Revise NAAQS PM2.5 to WHO 2021 standard</li></ul></div>', unsafe_allow_html=True)\n",
        "    st.divider()\n",
        "    st.subheader(\"State-level action plan\")\n",
        "    for _,row in merged.sort_values('Health_Index',ascending=False).iterrows():\n",
        "        badge_map = {'High Risk':'<span class=\"badge bc\">Critical</span>','Health Concern':'<span class=\"badge bh\">Health</span>',\n",
        "                     'Air Quality Concern':'<span class=\"badge bm\">Air</span>','Favourable':'<span class=\"badge bg\">OK</span>'}\n",
        "        with st.expander(f\"{row['State']}  —  AQI: {row['mean_AQI']:.0f}  {badge_map.get(row['Quadrant'],'')}\",\n",
        "                         expanded=False):\n",
        "            c1,c2 = st.columns(2)\n",
        "            with c1:\n",
        "                st.markdown(f\"**AQI:** {row['mean_AQI']:.1f} ({row['AQI_Category']})  \\n\"\n",
        "                            f\"**Anaemia:** {row['Anaemia_pct']:.1f}%  \\n\"\n",
        "                            f\"**Stunting:** {row['Stunting_pct']:.1f}%  \\n\"\n",
        "                            f\"**Underweight:** {row['Underweight_pct']:.1f}%  \\n\"\n",
        "                            f\"**Quadrant:** {row['Quadrant']}\")\n",
        "            with c2:\n",
        "                actions = {\n",
        "                    'High Risk':\"- Immediate IFA supplementation\\n- ASHA AQI alert system\\n- Source control for dominant pollutant\\n- ARI sentinel surveillance\",\n",
        "                    'Health Concern':\"- ICDS nutrition review\\n- Expand health monitoring\\n- Clean cooking fuel push\",\n",
        "                    'Air Quality Concern':\"- Preventive child health screening\\n- Industrial emission controls\\n- Monitor before health damage occurs\",\n",
        "                    'Favourable':\"- Document best practices\\n- Share with HIGH RISK states\\n- Continue NFHS monitoring\"\n",
        "                }\n",
        "                st.markdown(actions.get(row['Quadrant'],''))\n",
        "    st.divider()\n",
        "    pathway_data = {\n",
        "        'Pollutant':['PM2.5','PM10','NO₂','SO₂','O₃'],\n",
        "        'Pathway':['Bloodstream → hepcidin → iron suppression','Upper respiratory irritation',\n",
        "                   'Airway inflammation → lung development','Mucous membrane irritation','Oxidative stress → growth interference'],\n",
        "        'Child outcome':['Anaemia, underweight, stunting','ARI','ARI, stunting','ARI','Underweight, stunting'],\n",
        "        'Most affected':['Gujarat (484)','UP (224)','Haryana (235)','Jharkhand','Rajasthan']\n",
        "    }\n",
        "    st.subheader(\"Pollutant → health pathway\")\n",
        "    st.dataframe(pd.DataFrame(pathway_data), use_container_width=True)\n",
        "\n",
        "# ── PAGE 6: DISCUSSION ────────────────────────────────────────\n",
        "elif page == \"🗣️  Discussion Guide\":\n",
        "    st.title(\"🗣️ Discussion Guide\")\n",
        "    tab1,tab2,tab3 = st.tabs([\"❓ Q&A\",\"📣 Talking Points\",\"📝 Limitations\"])\n",
        "\n",
        "    with tab1:\n",
        "        qa = [\n",
        "            (\"Why non-parametric tests?\",\"Only 18 state-level observations after merging. OLS regression would be underpowered. Non-parametric tests use ranks — robust for small samples and skewed AQI distribution (range 44–484).\"),\n",
        "            (\"Correlation ≠ causation?\",\"Correct — cross-sectional ecological study. Association is consistent across 4 tests, biologically plausible (PM2.5 → hepcidin → anaemia), and aligns with literature. Goal is to identify intervention priorities, not prove causation.\"),\n",
        "            (\"Why only 18 states?\",\"CPCB monitors only 26 cities. After name harmonisation with NFHS-5, 18 states matched. Coverage gap itself is a finding — monitoring concentrated in urban/large states.\"),\n",
        "            (\"Why no ARI correlation (ρ=+0.046)?\",\"NFHS-5 ARI is 2-week recall with seasonal variation. Also strongly influenced by vaccination and healthcare access. ARI range is narrow (0.3–4.3%) limiting variance.\"),\n",
        "            (\"What is Cramér's V?\",\"Chi-square significance depends on sample size. Cramér's V (0–1) measures association strength independent of n. V=0.222 indicates consistent small-medium practical effect across nutritional outcomes.\"),\n",
        "            (\"Gujarat highest AQI but low ARI?\",\"Gujarat's extreme AQI (484) is industrial PM2.5 causing systemic effects (anaemia 79.8%, underweight 40.3%) rather than acute respiratory. Better healthcare may also reduce reported ARI.\"),\n",
        "        ]\n",
        "        for q,a in qa:\n",
        "            st.markdown(f'<div class=\"discuss\"><b>Q: {q}</b></div>', unsafe_allow_html=True)\n",
        "            with st.expander(\"Answer\"):\n",
        "                st.markdown(a)\n",
        "\n",
        "    with tab2:\n",
        "        for title,body in [\n",
        "            (\"The problem is real and measurable\",\"India has the world's highest PM2.5 levels AND highest child stunting. This study quantifies the link using NFHS-5 and CPCB simultaneously — a novel combination.\"),\n",
        "            (\"Indo-Gangetic Plain is a crisis zone\",\"Bihar, UP, West Bengal cluster in HIGH RISK. These 3 states hold ~350 million people. Targeted intervention here has the highest impact per rupee.\"),\n",
        "            (\"Effect sizes are large — not trivial\",\"r=−0.630 for anaemia and underweight is LARGE by Cohen's benchmarks. 11.4 percentage point anaemia gap between High and Low AQI states is clinically meaningful.\"),\n",
        "            (\"Non-parametric was methodologically correct\",\"With n=18 and AQI ranging 44–484, parametric assumptions cannot be met. This is rigour, not limitation.\"),\n",
        "            (\"Kerala shows what good looks like\",\"Anaemia 38.3%, stunting 23.3%, AQI 77.9 — Kerala proves low pollution and good child health co-occur and can be achieved through integrated policy.\"),\n",
        "        ]:\n",
        "            st.markdown(f'<div class=\"insight blue\"><b>{title}</b><br>{body}</div>', unsafe_allow_html=True)\n",
        "\n",
        "    with tab3:\n",
        "        st.subheader(\"Honest limitations\")\n",
        "        lims = {\n",
        "            \"Small n (18 states)\": \"Limits power for Kruskal–Wallis and Chi-square. Many moderate effects don't reach significance not because they're absent but because n is too small.\",\n",
        "            \"Ecological fallacy\": \"State-level aggregation masks within-state variation. A district-level analysis would be more precise.\",\n",
        "            \"Temporal mismatch\": \"CPCB 2015–2019 vs NFHS-5 2019–2021. Some pollution-health lag may exist.\",\n",
        "            \"Urban monitoring only\": \"CPCB stations are urban. Rural biomass burning pollution is not captured, potentially underestimating exposure in HIGH RISK states.\",\n",
        "            \"Uncontrolled confounders\": \"Poverty, sanitation, maternal education all affect child health and may correlate with AQI. Without controlling for these, residual confounding is possible.\",\n",
        "            \"Cross-sectional design\": \"Cannot establish causal direction. Reverse causality (poverty → both pollution and poor health) cannot be ruled out.\"\n",
        "        }\n",
        "        for lim, desc in lims.items():\n",
        "            with st.expander(lim):\n",
        "                st.markdown(desc)\n",
        "\n",
        "        st.subheader(\"Future work\")\n",
        "        st.markdown(\"\"\"\n",
        "        1. **Satellite PM2.5** (NASA MERRA-2 / Sentinel-5P) to extend to all 707 districts\n",
        "        2. **Longitudinal analysis** — compare NFHS-4 (2015–16) vs NFHS-5 (2019–21) to see if pollution improvements track health improvements\n",
        "        3. **Multilevel modelling** — nest districts within states to handle hierarchical structure\n",
        "        4. **Machine learning** — Random Forest to rank which factors best predict child health\n",
        "        5. **Cost-benefit analysis** — estimate DALYs averted if HIGH RISK states reach AQI &lt; 100\n",
        "        \"\"\")"
      ]
    },
    {
      "cell_type": "code",
      "source": [],
      "metadata": {
        "id": "2KyZQzLRnpYG"
      },
      "execution_count": null,
      "outputs": []
    }
  ]
}